### ISSUE TITLE
Implement experiment suite

### ISSUE THREAD

**Issue by hasanhaja** [hasanhaja/concurrency-rs#3]
# Todo
- [x] Write a clean up function
- [x] Parameterize processing functions
- [x] Use `#[inline]` directive to the functions being benchmarked
- [x] Write the other test cases
